# Generated by Django 4.1.6 on 2023-02-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='arquivo',
            new_name='imagem',
        ),
    ]
