# Generated by Django 4.1.6 on 2023-02-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_rename_arquivo_imagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='imagem',
            new_name='arquivo',
        ),
    ]
