# Generated by Django 4.1.6 on 2023-02-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0003_rename_imagem_imagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.ImageField(upload_to=''),
        ),
    ]
