FROM python:3.9

ENV ProcessorHOME=/home/app/webapp

RUN mkdir -p $ProcessorHOME

WORKDIR $ProcessorHOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY . $ProcessorHOME

RUN pip install -r requirements.txt


